@extends('layout/main')
@section('content')
  <h1 class="content--title">Alumnos</h1>
  <!-- student list -->
  <div class="row">
    <div class="col-sm-12">
      <div class="box-lg-flashcard">
    <table class="table">
      <thead>
        <td>Nombre</td>
        <td>Apellido</td>
        <td>Promedio</td>
      </thead>
      <tbody>
        <tr>
          <td>Alexis</td>
          <td>Dominguez</td>
          <td>97.5</td>
        </tr>
        <tr>
          <td>Mariana</td>
          <td>Milano</td>
          <td>96.5</td>
        </tr>
        <tr>
          <td>Julio</td>
          <td>Fernandez</td>
          <td>93.4</td>
        </tr>
        <tr>
          <td>Ana</td>
          <td>Perez</td>
          <td>92.8</td>
        </tr>
        <tr>
          <td>Sergio</td>
          <td>Tamez</td>
          <td>90.0</td>
        </tr>
        <tr>
          <td>Pedro</td>
          <td>Cantú</td>
          <td>89.2</td>
        </tr>
        <tr>
          <td>Ernesto</td>
          <td>Aguilar</td>
          <td>85.4</td>
        </tr>
        <tr>
          <td>Alexis</td>
          <td>Dominguez</td>
          <td>97.5</td>
        </tr>
        <tr>
          <td>Mariana</td>
          <td>Milano</td>
          <td>96.5</td>
        </tr>
        <tr>
          <td>Julio</td>
          <td>Fernandez</td>
          <td>93.4</td>
        </tr>
        <tr>
          <td>Ana</td>
          <td>Perez</td>
          <td>92.8</td>
        </tr>
        <tr>
          <td>Sergio</td>
          <td>Tamez</td>
          <td>90.0</td>
        </tr>
        <tr>
          <td>Pedro</td>
          <td>Cantú</td>
          <td>89.2</td>
        </tr>
        <tr>
          <td>Ernesto</td>
          <td>Aguilar</td>
          <td>85.4</td>
        </tr>
        <tr>
          <td>Alexis</td>
          <td>Dominguez</td>
          <td>97.5</td>
        </tr>
        <tr>
          <td>Mariana</td>
          <td>Milano</td>
          <td>96.5</td>
        </tr>
        <tr>
          <td>Julio</td>
          <td>Fernandez</td>
          <td>93.4</td>
        </tr>
        <tr>
          <td>Ana</td>
          <td>Perez</td>
          <td>92.8</td>
        </tr>
        <tr>
          <td>Sergio</td>
          <td>Tamez</td>
          <td>90.0</td>
        </tr>
        <tr>
          <td>Pedro</td>
          <td>Cantú</td>
          <td>89.2</td>
        </tr>
        <tr>
          <td>Ernesto</td>
          <td>Aguilar</td>
          <td>85.4</td>
        </tr>
        <tr>
          <td>Alexis</td>
          <td>Dominguez</td>
          <td>97.5</td>
        </tr>
        <tr>
          <td>Mariana</td>
          <td>Milano</td>
          <td>96.5</td>
        </tr>
        <tr>
          <td>Julio</td>
          <td>Fernandez</td>
          <td>93.4</td>
        </tr>
        <tr>
          <td>Ana</td>
          <td>Perez</td>
          <td>92.8</td>
        </tr>
        <tr>
          <td>Sergio</td>
          <td>Tamez</td>
          <td>90.0</td>
        </tr>
        <tr>
          <td>Pedro</td>
          <td>Cantú</td>
          <td>89.2</td>
        </tr>
        <tr>
          <td>Ernesto</td>
          <td>Aguilar</td>
          <td>85.4</td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>
  </div>
@endsection